name: C/C++ CI

on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches: [ "master" , "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: check minimake
      run: if [ -f minimake ]; then echo "minimake exists"; else echo "minimake does not exist"; fi
    - name: test with pytest
      run: pytest
